apiVersion: v1 
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-app
spec:
  replicas: 3
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
      namespace: frontend
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80 

        - name: tomcat-container
          image: tomcat
          ports: 
            - containerPort: 8080